In [8]:
import torch

print("Torch version:",torch.__version__)

print("Is CUDA enabled?",torch.cuda.is_available())

Torch version: 2.2.1
Is CUDA enabled? True


In [1]:
from numpy import load

data = load('./public_data/bmvs_clock/cameras_sphere.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])

world_mat_0
[[-8.1202429e+02 -2.0498053e+02  1.3244104e+03  4.5049033e+02]
 [-9.6825415e+02  1.1589094e+03 -3.3458234e+02  3.3499899e+02]
 [-8.0637997e-01 -5.1539701e-01 -2.9003000e-01  1.1773100e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
scale_mat_0
[[0.32525897 0.         0.         0.03669082]
 [0.         0.32525897 0.         0.00434226]
 [0.         0.         0.32525897 0.01745793]
 [0.         0.         0.         1.        ]]
world_mat_1
[[ 2.3431096e+02 -1.8993645e+02  1.5376881e+03  4.5291370e+02]
 [-9.5913782e+02  1.1594854e+03  3.5802661e+02  3.3591431e+02]
 [-8.0176997e-01 -5.1494902e-01  3.0330101e-01  1.1785800e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
scale_mat_1
[[0.32525897 0.         0.         0.03669082]
 [0.         0.32525897 0.         0.00434226]
 [0.         0.         0.32525897 0.01745793]
 [0.         0.         0.         1.        ]]
world_mat_2
[[ 1.1717323e+03 -1.7656557e+02  1.0253439e+03  4.543377

In [9]:
# Python program to explain os.sysconf() method 
	
# importing os module 
import os 

os.sysconf()


AttributeError: module 'os' has no attribute 'sysconf'